---
:sources:
  :time-tech:
    :base: http://time.com/section/tech
    :article_base: http://time.com
    :xpath: //div[@class="row _1An5xv1b"]//a[@target="_self"]
  :facebook-blog:
    :base: https://code.facebook.com
    :article_base: https://code.facebook.com
    :xpath: //div[@class="_5mr _iuj _cql"]//a
  # :google-blog:
  #   :base: https://blog.google
  #   :article_base: https://blog.google
  #   :xpath: 
  :twilio-press:
    :base: https://twilio.com/press/releases
    :article_base: https://twilio.com
    :xpath: //div[@class="column-5-6 "]//a
  :twilio-blog:
    :base: https://www.twilio.com/blog
    :article_base: ''
    :xpath: //h2[@class="entry-title"]//a
  :thumbtack-blog:
    :base: http://thumbtack.com/engineering
    :article_base: ''
    :xpath: //h2//a
  :target-blog:
    :base: http://target.github.io/
    :article_base: http://
    :xpath: //h2//a