---
:sources:
  :time_tech:
    :base: http://time.com/section/tech
    :article_base: http://time.com
  :facebook_blog:
    :base: https://code.facebook.com
    :article_base: https://code.facebook.com
  :google_blog:
    :base: https://blog.google
    :article_base: https://blog.google
  :twilio_press:
    :base: https://twilio.com/press/releases
    :article_base: https://twilio.com